-- delete all the plans in baselines
SET SERVEROUTPUT ON
DECLARE
	n PLS_INTEGER;
	m PLS_INTEGER;
BEGIN
	FOR R IN (SELECT SQL_HANDLE FROM DBA_SQL_PLAN_BASELINES) LOOP
		BEGIN
			n := DBMS_SPM.DROP_SQL_PLAN_BASELINE ( R.SQL_HANDLE );
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
		END;
	END LOOP;
-- verify:
	SELECT COUNT(SQL_HANDLE) INTO M FROM DBA_SQL_PLAN_BASELINES;
	IF M = 0 THEN
		DBMS_OUTPUT.PUT_LINE('Baselines deleted.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('Baselines could not be deleted!');
	END IF;
END;
/