col COLUMN_NAME format a14

SELECT 
	C.COLUMN_NAME, 
	EQUIJOIN_PREDS, 
	NONEQUIJOIN_PREDS, 
	RANGE_PREDS,
	LIKE_PREDS, 
	NULL_PREDS
FROM 
	SYS.COL_USAGE$ CU, 
	DBA_OBJECTS O, 
	DBA_TAB_COLUMNS C
WHERE O.OBJECT_ID = CU.OBJ# AND (O.OBJECT_NAME=C.TABLE_NAME AND C.COLUMN_ID = CU.INTCOL#) AND OBJECT_NAME='ORDERS2'
ORDER BY OBJECT_NAME, C.COLUMN_ID;