col IS_RESOLVED_ADAPTIVE_PLAN format a25
col IS_REOPTIMIZABLE format a16
SELECT 
	SQL_ID, 
	CHILD_NUMBER, 
	PLAN_HASH_VALUE, 
	IS_RESOLVED_ADAPTIVE_PLAN IS_RESOLVED_ADAPTIVE_PLAN,
	IS_REOPTIMIZABLE IS_REOPTIMIZABLE
FROM 
	V$SQL 
WHERE SQL_ID='&v_sql_id' ORDER BY SQL_ID, CHILD_NUMBER;