set termout off
SELECT /*+ GATHER_PLAN_STATISTICS */ 
O.ORDER_ID, O.ORDER_STATUS, OL.PRODUCT_ID, OL.UNIT_PRICE, OL.QUANTITY
FROM SOE.ORDERS O
INNER JOIN
SOE.ORDER_ITEMS OL
ON O.ORDER_ID = OL.ORDER_ID
FETCH FIRST 10000 ROWS ONLY;